"""Self-play conversation generator with inline teacher target capture.

Runs Moshi in self-play mode: the model's own audio output (Channel B) is
fed back as user input (Channel A) at the next timestep, producing a
realistic full-duplex conversation without any external audio.

Architecture reference (Moshiko):
    n_q=16     — 16 audio codebook streams in total
    dep_q=8    — Depformer generates 8 codebooks (model's audio, Channel B)
    needed_tokens = num_codebooks - dep_q - 1 = 17 - 8 - 1 = 8
    → LMGen.step() requires 8 user audio codebooks (Channel A) per timestep

    delays = [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1]
    Index 0:  text (Inner Monologue)
    Index 1-8:  model audio CB0..7 (generated by Depformer)
    Index 9-16: user audio CB0..7 (provided as input)

Self-play loop:
    t=0: Feed seed tokens as Channel A → model generates Channel B
    t=1: Feed model's Channel B output from t=0 as Channel A → generates B
    ...repeat for N timesteps
"""

import json
import time
import numpy as np
import torch
from pathlib import Path
from dataclasses import dataclass, asdict
from tqdm import tqdm

from .target_capture import TeacherTargetCapture, StepTargets
from .quality_filter import filter_conversation, QualityReport


class TextRepetitionPenalty:
    """Applies repetition penalty to text logits during generation.

    Hooks into LMGen.on_text_logits_hook to modify logits in-place,
    penalizing recently-generated text tokens to prevent loops.

    Installed BEFORE TeacherTargetCapture so that capture records the
    original (unpenalized) teacher logits, then this hook penalizes
    for diverse sampling.
    """

    def __init__(self, penalty: float = 1.3, window: int = 50):
        self.penalty = penalty
        self.window = window
        self.recent_tokens: list[int] = []

    def update(self, token: int):
        """Record a generated text token (call after each step)."""
        if token > 3:  # Skip PAD/BOS/EOS/UNK
            self.recent_tokens.append(token)
            if len(self.recent_tokens) > self.window:
                self.recent_tokens.pop(0)

    def hook(self, logits: torch.Tensor):
        """Modify logits in-place to penalize recently seen tokens.

        Args:
            logits: [B, 1, 1, text_card] — text logits before sampling.
        """
        if not self.recent_tokens or self.penalty <= 1.0:
            return
        logit_vec = logits[0, 0, 0]
        for token in set(self.recent_tokens):
            if token < logit_vec.shape[0]:
                if logit_vec[token] > 0:
                    logit_vec[token] /= self.penalty
                else:
                    logit_vec[token] *= self.penalty


@dataclass
class ConversationRecord:
    """All data from a single self-play conversation, ready to save as .npz."""
    conv_id: str
    text_tokens: np.ndarray         # [T], int16
    audio_tokens: np.ndarray        # [dep_q=8, T], int16
    text_logits_vals: np.ndarray    # [T, top_k], float16
    text_logits_idxs: np.ndarray    # [T, top_k], int32
    audio_cb0_logits_vals: np.ndarray  # [T, top_k], float16
    audio_cb0_logits_idxs: np.ndarray  # [T, top_k], int32
    user_audio_tokens: np.ndarray   # [8, T], int16 — what was fed as Channel A
    num_valid_steps: int
    seed_type: str
    temperature: float
    quality: QualityReport | None


def _make_seed_tokens(
    seed_type: str,
    seed_index: int,
    num_codebooks: int = 8,
    card: int = 2048,
    device: str = "cuda",
) -> torch.Tensor:
    """Generate seed tokens for Channel A (user audio) at the first timestep.

    Args:
        seed_type: One of "noise", "acoustic", "silence".
        seed_index: RNG seed for reproducibility.
        num_codebooks: Number of user audio codebooks (8 for Moshiko).
        card: Audio codebook vocabulary size (2048 for Moshiko).
        device: Torch device.

    Returns:
        Tensor of shape [1, num_codebooks, 1] (one timestep of user audio).
    """
    rng = torch.Generator(device="cpu").manual_seed(seed_index)

    if seed_type == "noise":
        # Random codebook tokens — forces diverse acoustic context
        tokens = torch.randint(0, card, (1, num_codebooks, 1), generator=rng)
    elif seed_type == "acoustic":
        # Random but constrained: each codebook gets a token from a
        # smaller range to simulate more structured audio
        tokens = torch.randint(0, card // 4, (1, num_codebooks, 1), generator=rng)
    elif seed_type == "silence":
        # All zeros — silence seed
        tokens = torch.zeros(1, num_codebooks, 1, dtype=torch.long)
    else:
        raise ValueError(f"Unknown seed_type: {seed_type}")

    return tokens.to(device=device)


def generate_conversation(
    lm_gen,
    num_steps: int = 3750,
    seed_type: str = "noise",
    seed_index: int = 0,
    top_k_logits: int = 50,
    conv_id: str = "conv_000000",
    card: int = 2048,
    device: str = "cuda",
    repetition_penalty: float = 1.3,
    rep_window: int = 50,
) -> ConversationRecord:
    """Run a single self-play conversation with inline target capture.

    Args:
        lm_gen: An LMGen instance (must NOT be in streaming mode yet).
        num_steps: Number of timesteps to generate (3750 ≈ 5 minutes).
        seed_type: Type of seed for Channel A at t=0.
        seed_index: RNG seed for the seed token generator.
        top_k_logits: Number of top logits to capture per step.
        conv_id: Identifier for this conversation.
        card: Audio codebook vocabulary size.
        device: Torch device.
        repetition_penalty: Penalty for repeated text tokens (1.0=off, >1.0=penalize).
        rep_window: Number of recent non-PAD text tokens to track.

    Returns:
        ConversationRecord with all captured targets.
    """
    lm_model = lm_gen.lm_model
    dep_q = lm_model.dep_q
    # User input codebooks = total audio - depformer audio = n_q - dep_q
    n_user_codebooks = lm_model.n_q - dep_q  # = 8 for Moshiko
    max_delay = lm_gen.max_delay

    # Install repetition penalty hook (modifies logits for diverse sampling)
    rep_penalty = TextRepetitionPenalty(
        penalty=repetition_penalty, window=rep_window
    )
    if repetition_penalty > 1.0:
        lm_gen.on_text_logits_hook = rep_penalty.hook

    # Install target capture hooks (chains with penalty — captures original
    # logits first, then penalty modifies in-place for sampling)
    capture = TeacherTargetCapture(lm_gen, top_k=top_k_logits)
    capture.install_hooks()

    # Accumulate per-step targets
    all_text_tokens = []
    all_audio_tokens = []
    all_text_logits_vals = []
    all_text_logits_idxs = []
    all_audio_cb0_logits_vals = []
    all_audio_cb0_logits_idxs = []
    all_user_audio = []

    num_valid = 0
    seed_tokens = _make_seed_tokens(seed_type, seed_index, n_user_codebooks, card, device)

    try:
        with lm_gen.streaming(batch_size=1):
            # prev_model_audio: the model's Channel B output from previous step,
            # to be fed back as Channel A input.
            prev_model_audio = seed_tokens  # [1, 8, 1]

            for t in range(num_steps):
                # Feed Channel A (previous model output or seed)
                out = lm_gen.step(prev_model_audio)

                # Capture targets
                targets = capture.pop_step_targets()

                if out is None:
                    # Still filling delay buffer — no valid output yet
                    continue

                # out shape: [1, dep_q + 1, 1] = [1, 9, 1]
                # out[:, 0] = text token
                # out[:, 1:] = model audio CB0..7
                out_squeezed = out[0, :, 0]  # [dep_q + 1 = 9]
                text_tok = out_squeezed[0].item()
                rep_penalty.update(text_tok)
                model_audio = out_squeezed[1:]  # [dep_q = 8]

                # Feed model's audio back as next step's user input
                # Shape: [1, n_user_codebooks, 1]
                prev_model_audio = model_audio.unsqueeze(0).unsqueeze(-1).long()

                # Store user-side audio that was fed (before this step)
                all_user_audio.append(
                    prev_model_audio[0, :, 0].cpu().to(torch.int16).numpy()
                )

                if targets is not None:
                    all_text_tokens.append(targets.text_token)
                    all_audio_tokens.append(targets.audio_tokens.numpy())
                    all_text_logits_vals.append(targets.text_logits_vals.numpy())
                    all_text_logits_idxs.append(targets.text_logits_idxs.numpy())
                    all_audio_cb0_logits_vals.append(targets.audio_cb0_logits_vals.numpy())
                    all_audio_cb0_logits_idxs.append(targets.audio_cb0_logits_idxs.numpy())
                    num_valid += 1
                else:
                    # Targets not captured (shouldn't happen after delay fill)
                    all_text_tokens.append(text_tok)
                    all_audio_tokens.append(model_audio.cpu().to(torch.int16).numpy())
                    # Pad logits with zeros
                    all_text_logits_vals.append(np.zeros(top_k_logits, dtype=np.float16))
                    all_text_logits_idxs.append(np.zeros(top_k_logits, dtype=np.int32))
                    all_audio_cb0_logits_vals.append(np.zeros(top_k_logits, dtype=np.float16))
                    all_audio_cb0_logits_idxs.append(np.zeros(top_k_logits, dtype=np.int32))
                    num_valid += 1

    finally:
        capture.remove_hooks()
        lm_gen.on_text_logits_hook = None  # Clear repetition penalty

    if num_valid == 0:
        # Edge case: no valid output at all (shouldn't happen with enough steps)
        raise RuntimeError(
            f"No valid output produced in {num_steps} steps. "
            f"max_delay={max_delay}, try increasing num_steps."
        )

    # Stack into arrays
    text_tokens = np.array(all_text_tokens, dtype=np.int16)
    audio_tokens = np.stack(all_audio_tokens, axis=-1).astype(np.int16)  # [8, T]
    text_logits_vals = np.stack(all_text_logits_vals).astype(np.float16)  # [T, top_k]
    text_logits_idxs = np.stack(all_text_logits_idxs).astype(np.int32)
    audio_cb0_logits_vals = np.stack(all_audio_cb0_logits_vals).astype(np.float16)
    audio_cb0_logits_idxs = np.stack(all_audio_cb0_logits_idxs).astype(np.int32)
    user_audio = np.stack(all_user_audio, axis=-1).astype(np.int16) if all_user_audio else np.zeros((8, 0), dtype=np.int16)

    return ConversationRecord(
        conv_id=conv_id,
        text_tokens=text_tokens,
        audio_tokens=audio_tokens,
        text_logits_vals=text_logits_vals,
        text_logits_idxs=text_logits_idxs,
        audio_cb0_logits_vals=audio_cb0_logits_vals,
        audio_cb0_logits_idxs=audio_cb0_logits_idxs,
        user_audio_tokens=user_audio,
        num_valid_steps=num_valid,
        seed_type=seed_type,
        temperature=0.0,  # set by caller from LMGen config
        quality=None,     # filled after quality filtering
    )


def save_conversation(record: ConversationRecord, output_dir: Path) -> Path:
    """Save a ConversationRecord as a compressed .npz file.

    Args:
        record: The conversation data.
        output_dir: Directory to save into (will be created if needed).

    Returns:
        Path to the saved .npz file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{record.conv_id}.npz"

    np.savez_compressed(
        str(path),
        text_tokens=record.text_tokens,
        audio_tokens=record.audio_tokens,
        text_logits_vals=record.text_logits_vals,
        text_logits_idxs=record.text_logits_idxs,
        audio_cb0_logits_vals=record.audio_cb0_logits_vals,
        audio_cb0_logits_idxs=record.audio_cb0_logits_idxs,
        user_audio_tokens=record.user_audio_tokens,
        num_valid_steps=np.array([record.num_valid_steps], dtype=np.int32),
    )
    return path


def generate_batch(
    lm_gen,
    num_conversations: int = 480,
    steps_per_conversation: int = 3750,
    seed_types: list[str] | None = None,
    seed_type_weights: list[float] | None = None,
    top_k_logits: int = 50,
    output_dir: str | Path = "/content/drive/MyDrive/moshilite/self_play_data/conversations",
    batch_id: str = "batch_000",
    start_index: int = 0,
    card: int = 2048,
    device: str = "cuda",
    save_rejected: bool = False,
    repetition_penalty: float = 1.3,
    rep_window: int = 50,
) -> dict:
    """Generate a batch of self-play conversations with quality filtering.

    Args:
        lm_gen: An LMGen instance.
        num_conversations: Target number of accepted conversations.
        steps_per_conversation: Timesteps per conversation (375 ≈ 30s).
        seed_types: List of seed types to sample from.
        seed_type_weights: Probability weights for seed types.
        top_k_logits: Number of top logits to capture.
        output_dir: GDrive path for saving conversations.
        batch_id: Identifier for this generation session.
        start_index: Starting conversation index (for multi-session support).
        card: Audio codebook vocabulary size.
        device: Torch device.
        save_rejected: Whether to save rejected conversations (for analysis).

    Returns:
        Dict with generation statistics.
    """
    if seed_types is None:
        seed_types = ["noise", "acoustic", "silence"]
    if seed_type_weights is None:
        seed_type_weights = [0.8, 0.1, 0.1]

    output_path = Path(output_dir) / batch_id
    output_path.mkdir(parents=True, exist_ok=True)

    # Resume support: detect existing conversations from a previous session
    existing_convs = {f.stem for f in output_path.glob("conv_*.npz")}
    num_existing = len(existing_convs)

    # Get temperature from lm_gen
    temperature = getattr(lm_gen, "temp", 0.8)

    # Stats
    stats = {
        "batch_id": batch_id,
        "target_conversations": num_conversations,
        "accepted": num_existing,
        "rejected": 0,
        "rejection_reasons": {},
        "total_valid_steps": 0,
        "total_wall_time_s": 0.0,
        "per_seed_type": {st: {"accepted": 0, "rejected": 0} for st in seed_types},
        "resumed_from": num_existing,
    }

    # RNG for seed type selection
    rng = np.random.default_rng(seed=start_index)
    weights = np.array(seed_type_weights, dtype=np.float64)
    weights /= weights.sum()

    attempt = 0
    t_start = time.time()

    if num_existing > 0:
        print(f"📂 Resuming: found {num_existing} existing conversations in {output_path}")

    pbar = tqdm(total=num_conversations, initial=num_existing,
                desc=f"Generating {batch_id}")

    while stats["accepted"] < num_conversations:
        seed_idx = start_index + attempt
        seed_type = rng.choice(seed_types, p=weights)  # Always advance RNG
        conv_id = f"conv_{seed_idx:06d}"

        # Resume: skip conversations that already exist on disk
        if conv_id in existing_convs:
            attempt += 1
            continue

        try:
            record = generate_conversation(
                lm_gen=lm_gen,
                num_steps=steps_per_conversation,
                seed_type=seed_type,
                seed_index=seed_idx,
                top_k_logits=top_k_logits,
                conv_id=conv_id,
                card=card,
                device=device,
                repetition_penalty=repetition_penalty,
                rep_window=rep_window,
            )
            record.temperature = temperature

            # Quality filter
            quality = filter_conversation(
                text_tokens=record.text_tokens,
                audio_tokens=record.audio_tokens,
                num_valid_steps=record.num_valid_steps,
            )
            record.quality = quality

            if quality.accepted:
                save_conversation(record, output_path)
                stats["accepted"] += 1
                stats["total_valid_steps"] += record.num_valid_steps
                stats["per_seed_type"][seed_type]["accepted"] += 1
                pbar.update(1)
            else:
                stats["rejected"] += 1
                reason = quality.rejection_reason or "unknown"
                stats["rejection_reasons"][reason] = stats["rejection_reasons"].get(reason, 0) + 1
                stats["per_seed_type"][seed_type]["rejected"] += 1
                if save_rejected:
                    rejected_dir = output_path / "rejected"
                    save_conversation(record, rejected_dir)

        except Exception as e:
            stats["rejected"] += 1
            reason = f"error: {type(e).__name__}"
            stats["rejection_reasons"][reason] = stats["rejection_reasons"].get(reason, 0) + 1
            print(f"⚠️  Error generating {conv_id}: {e}")

        attempt += 1

        # Safety: prevent infinite loop if everything is rejected
        if attempt > num_conversations * 3:
            print(f"⚠️  Giving up after {attempt} attempts "
                  f"({stats['accepted']} accepted, {stats['rejected']} rejected)")
            break

    pbar.close()
    stats["total_wall_time_s"] = time.time() - t_start
    stats["total_attempts"] = attempt
    stats["acceptance_rate"] = stats["accepted"] / max(1, attempt)
    stats["total_audio_hours"] = (
        stats["total_valid_steps"] / 12.5 / 3600  # 12.5 Hz → seconds → hours
    )

    # Save batch metadata
    meta_path = output_path / "batch_meta.json"
    with open(meta_path, "w") as f:
        json.dump(stats, f, indent=2, default=str)
    print(f"\n✅ Batch {batch_id}: {stats['accepted']} conversations, "
          f"{stats['total_audio_hours']:.2f} hours, "
          f"{stats['total_wall_time_s'] / 60:.1f} min wall time, "
          f"{stats['acceptance_rate']:.1%} acceptance rate")

    return stats


# ============================================================================
# CROSS-PLAY GENERATION
# Two independent Moshi teacher instances converse with each other,
# producing higher-quality training data than self-play (where a model
# merely echoes itself).
# ============================================================================


@dataclass
class CrossPlayRecord:
    """All data from a single cross-play conversation (two models talking).

    Contains teacher targets from BOTH models.  When saved, this is split
    into two standard-format .npz files (one per model) that are fully
    compatible with the existing SelfPlayDataset.
    """
    conv_id: str

    # ── Model A targets ──
    a_text_tokens: np.ndarray           # [T], int16
    a_audio_tokens: np.ndarray          # [dep_q=8, T], int16
    a_text_logits_vals: np.ndarray      # [T, top_k], float16
    a_text_logits_idxs: np.ndarray      # [T, top_k], int32
    a_audio_cb0_logits_vals: np.ndarray # [T, top_k], float16
    a_audio_cb0_logits_idxs: np.ndarray # [T, top_k], int32
    a_user_audio_tokens: np.ndarray     # [8, T], int16 — Model B's output fed to A

    # ── Model B targets ──
    b_text_tokens: np.ndarray           # [T], int16
    b_audio_tokens: np.ndarray          # [dep_q=8, T], int16
    b_text_logits_vals: np.ndarray      # [T, top_k], float16
    b_text_logits_idxs: np.ndarray      # [T, top_k], int32
    b_audio_cb0_logits_vals: np.ndarray # [T, top_k], float16
    b_audio_cb0_logits_idxs: np.ndarray # [T, top_k], int32
    b_user_audio_tokens: np.ndarray     # [8, T], int16 — Model A's output fed to B

    # ── Shared metadata ──
    num_valid_steps: int
    seed_type: str
    temperature: float
    quality_a: QualityReport | None
    quality_b: QualityReport | None


def generate_cross_play_conversation(
    lm_gen_a,
    lm_gen_b,
    num_steps: int = 3750,
    seed_type: str = "noise",
    seed_index: int = 0,
    top_k_logits: int = 1000,
    conv_id: str = "conv_000000",
    card: int = 2048,
    device: str = "cuda",
    repetition_penalty: float = 1.3,
    rep_window: int = 50,
) -> CrossPlayRecord:
    """Run a single cross-play conversation between two Moshi models.

    Both models run in full-duplex mode: Model A hears Model B's previous
    output, and Model B hears Model A's current output.  Teacher targets
    (top-k logits, hard tokens) are captured from both models independently.

    Args:
        lm_gen_a: LMGen for Model A (must NOT be in streaming mode yet).
        lm_gen_b: LMGen for Model B (must NOT be in streaming mode yet).
        num_steps: Timesteps to generate (3750 ≈ 5 minutes at 12.5 Hz).
        seed_type: Seed for Channel A at t=0 ("noise"/"acoustic"/"silence").
        seed_index: RNG seed for the seed token generator.
        top_k_logits: Number of top logits to capture per step (1000 for
            richer offline distillation signal).
        conv_id: Unique identifier for this conversation.
        card: Audio codebook vocabulary size (2048 for Moshiko).
        device: Torch device.
        repetition_penalty: Penalty for repeated text tokens (>1.0 penalizes).
        rep_window: Sliding window size for repetition tracking.

    Returns:
        CrossPlayRecord with targets from both models.
    """
    lm_model_a = lm_gen_a.lm_model
    lm_model_b = lm_gen_b.lm_model
    dep_q = lm_model_a.dep_q
    n_user_codebooks = lm_model_a.n_q - dep_q  # 8 for Moshiko

    # ── Install independent repetition penalty hooks ──
    rep_a = TextRepetitionPenalty(penalty=repetition_penalty, window=rep_window)
    rep_b = TextRepetitionPenalty(penalty=repetition_penalty, window=rep_window)
    if repetition_penalty > 1.0:
        lm_gen_a.on_text_logits_hook = rep_a.hook
        lm_gen_b.on_text_logits_hook = rep_b.hook

    # ── Install independent target capture hooks ──
    capture_a = TeacherTargetCapture(lm_gen_a, top_k=top_k_logits)
    capture_b = TeacherTargetCapture(lm_gen_b, top_k=top_k_logits)
    capture_a.install_hooks()
    capture_b.install_hooks()

    # ── Accumulators for Model A ──
    a_text_toks, a_audio_toks = [], []
    a_tl_vals, a_tl_idxs = [], []
    a_al_vals, a_al_idxs = [], []
    a_user_audio = []

    # ── Accumulators for Model B ──
    b_text_toks, b_audio_toks = [], []
    b_tl_vals, b_tl_idxs = [], []
    b_al_vals, b_al_idxs = [], []
    b_user_audio = []

    num_valid = 0
    seed_tokens = _make_seed_tokens(
        seed_type, seed_index, n_user_codebooks, card, device
    )

    try:
        with lm_gen_a.streaming(batch_size=1), lm_gen_b.streaming(batch_size=1):
            prev_b_output = seed_tokens  # [1, 8, 1] — initial input for Model A

            for t in range(num_steps):
                # ── Step 1: Model A receives Model B's previous output ──
                out_a = lm_gen_a.step(prev_b_output)
                targets_a = capture_a.pop_step_targets()

                if out_a is not None:
                    out_a_sq = out_a[0, :, 0]         # [dep_q + 1 = 9]
                    txt_a = out_a_sq[0].item()
                    audio_a = out_a_sq[1:]              # [dep_q = 8]
                    rep_a.update(txt_a)
                    input_for_b = audio_a.unsqueeze(0).unsqueeze(-1).long()
                else:
                    input_for_b = seed_tokens

                # ── Step 2: Model B receives Model A's current output ──
                out_b = lm_gen_b.step(input_for_b)
                targets_b = capture_b.pop_step_targets()

                if out_b is not None:
                    out_b_sq = out_b[0, :, 0]
                    txt_b = out_b_sq[0].item()
                    audio_b = out_b_sq[1:]
                    rep_b.update(txt_b)
                    prev_b_output = audio_b.unsqueeze(0).unsqueeze(-1).long()
                else:
                    prev_b_output = seed_tokens

                # ── Accumulate only when BOTH models produced output ──
                if out_a is not None and out_b is not None:
                    # Model A targets
                    _store_step(
                        targets_a, txt_a, audio_a,
                        prev_b_output,  # what A received = B's output from prev step
                        a_text_toks, a_audio_toks,
                        a_tl_vals, a_tl_idxs, a_al_vals, a_al_idxs,
                        a_user_audio, top_k_logits,
                    )
                    # Model B targets
                    _store_step(
                        targets_b, txt_b, audio_b,
                        input_for_b,  # what B received = A's current output
                        b_text_toks, b_audio_toks,
                        b_tl_vals, b_tl_idxs, b_al_vals, b_al_idxs,
                        b_user_audio, top_k_logits,
                    )
                    num_valid += 1

    finally:
        capture_a.remove_hooks()
        capture_b.remove_hooks()
        lm_gen_a.on_text_logits_hook = None
        lm_gen_b.on_text_logits_hook = None

    if num_valid == 0:
        raise RuntimeError(
            f"No valid output produced in {num_steps} cross-play steps."
        )

    return CrossPlayRecord(
        conv_id=conv_id,
        # Model A
        a_text_tokens=np.array(a_text_toks, dtype=np.int16),
        a_audio_tokens=np.stack(a_audio_toks, axis=-1).astype(np.int16),
        a_text_logits_vals=np.stack(a_tl_vals).astype(np.float16),
        a_text_logits_idxs=np.stack(a_tl_idxs).astype(np.int32),
        a_audio_cb0_logits_vals=np.stack(a_al_vals).astype(np.float16),
        a_audio_cb0_logits_idxs=np.stack(a_al_idxs).astype(np.int32),
        a_user_audio_tokens=(
            np.stack(a_user_audio, axis=-1).astype(np.int16)
            if a_user_audio else np.zeros((8, 0), dtype=np.int16)
        ),
        # Model B
        b_text_tokens=np.array(b_text_toks, dtype=np.int16),
        b_audio_tokens=np.stack(b_audio_toks, axis=-1).astype(np.int16),
        b_text_logits_vals=np.stack(b_tl_vals).astype(np.float16),
        b_text_logits_idxs=np.stack(b_tl_idxs).astype(np.int32),
        b_audio_cb0_logits_vals=np.stack(b_al_vals).astype(np.float16),
        b_audio_cb0_logits_idxs=np.stack(b_al_idxs).astype(np.int32),
        b_user_audio_tokens=(
            np.stack(b_user_audio, axis=-1).astype(np.int16)
            if b_user_audio else np.zeros((8, 0), dtype=np.int16)
        ),
        # Shared
        num_valid_steps=num_valid,
        seed_type=seed_type,
        temperature=0.0,  # set by caller
        quality_a=None,
        quality_b=None,
    )


def _store_step(
    targets: "StepTargets | None",
    text_tok: int,
    audio: torch.Tensor,
    user_input: torch.Tensor,
    text_list: list,
    audio_list: list,
    tl_vals: list,
    tl_idxs: list,
    al_vals: list,
    al_idxs: list,
    user_audio_list: list,
    top_k: int,
):
    """Accumulate one step's data into the per-model lists."""
    if targets is not None:
        text_list.append(targets.text_token)
        audio_list.append(targets.audio_tokens.numpy())
        tl_vals.append(targets.text_logits_vals.numpy())
        tl_idxs.append(targets.text_logits_idxs.numpy())
        al_vals.append(targets.audio_cb0_logits_vals.numpy())
        al_idxs.append(targets.audio_cb0_logits_idxs.numpy())
    else:
        text_list.append(text_tok)
        audio_list.append(audio.cpu().to(torch.int16).numpy())
        tl_vals.append(np.zeros(top_k, dtype=np.float16))
        tl_idxs.append(np.zeros(top_k, dtype=np.int32))
        al_vals.append(np.zeros(top_k, dtype=np.float16))
        al_idxs.append(np.zeros(top_k, dtype=np.int32))
    user_audio_list.append(
        user_input[0, :, 0].cpu().to(torch.int16).numpy()
    )


def save_cross_play_conversation(
    record: CrossPlayRecord, output_dir: Path
) -> tuple[Path, Path]:
    """Save a CrossPlayRecord as two standard-format .npz files.

    Splits the dual-model record into ``{conv_id}_modelA.npz`` and
    ``{conv_id}_modelB.npz``.  Each file has the **exact same schema** as
    self-play ``.npz`` files, so the existing ``SelfPlayDataset`` discovers
    and loads them seamlessly.

    Returns:
        Tuple of (path_a, path_b).
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    def _save_side(prefix: str, text, audio, tl_v, tl_i, al_v, al_i, user) -> Path:
        path = output_dir / f"{record.conv_id}_{prefix}.npz"
        np.savez_compressed(
            str(path),
            text_tokens=text,
            audio_tokens=audio,
            text_logits_vals=tl_v,
            text_logits_idxs=tl_i,
            audio_cb0_logits_vals=al_v,
            audio_cb0_logits_idxs=al_i,
            user_audio_tokens=user,
            num_valid_steps=np.array([record.num_valid_steps], dtype=np.int32),
        )
        return path

    path_a = _save_side(
        "modelA",
        record.a_text_tokens, record.a_audio_tokens,
        record.a_text_logits_vals, record.a_text_logits_idxs,
        record.a_audio_cb0_logits_vals, record.a_audio_cb0_logits_idxs,
        record.a_user_audio_tokens,
    )
    path_b = _save_side(
        "modelB",
        record.b_text_tokens, record.b_audio_tokens,
        record.b_text_logits_vals, record.b_text_logits_idxs,
        record.b_audio_cb0_logits_vals, record.b_audio_cb0_logits_idxs,
        record.b_user_audio_tokens,
    )
    return path_a, path_b


def generate_cross_play_batch(
    lm_gen_a,
    lm_gen_b,
    num_conversations: int = 48,
    steps_per_conversation: int = 3750,
    seed_types: list[str] | None = None,
    seed_type_weights: list[float] | None = None,
    top_k_logits: int = 1000,
    output_dir: str | Path = "/content/drive/MyDrive/moshilite/self_play_data/conversations",
    batch_id: str = "xplay_000",
    start_index: int = 0,
    card: int = 2048,
    device: str = "cuda",
    save_rejected: bool = False,
    repetition_penalty: float = 1.3,
    rep_window: int = 50,
) -> dict:
    """Generate a batch of cross-play conversations with quality filtering.

    Two Moshi teacher models converse in full-duplex mode.  Each conversation
    produces **two** ``.npz`` files (one per model) in the standard format,
    compatible with the existing ``SelfPlayDataset``.

    The batch is **incrementally appendable**: re-running with the same
    ``batch_id`` discovers existing ``.npz`` files and skips them, so you
    can grow the dataset across sessions without losing progress.

    Args:
        lm_gen_a: LMGen for Model A.
        lm_gen_b: LMGen for Model B.
        num_conversations: Target number of accepted conversations.
        steps_per_conversation: Timesteps per conv (3750 ≈ 5 min).
        seed_types: Seed types to sample from.
        seed_type_weights: Probability weights for seed types.
        top_k_logits: Number of top logits to capture per step.
        output_dir: GDrive path for output.
        batch_id: Batch identifier (use "xplay_" prefix to distinguish
            from self-play batches).
        start_index: Starting conversation index.
        card: Audio codebook vocabulary size.
        device: Torch device.
        save_rejected: Whether to save rejected conversations.
        repetition_penalty: Penalty for repeated text tokens.
        rep_window: Sliding window for repetition tracking.

    Returns:
        Dict with generation statistics.
    """
    if seed_types is None:
        seed_types = ["noise", "acoustic", "silence"]
    if seed_type_weights is None:
        seed_type_weights = [0.8, 0.1, 0.1]

    output_path = Path(output_dir) / batch_id
    output_path.mkdir(parents=True, exist_ok=True)

    # Resume: detect existing conversation pairs from a previous session.
    # A completed cross-play conversation has BOTH _modelA.npz and _modelB.npz.
    existing_a = {f.stem.replace("_modelA", "") for f in output_path.glob("conv_*_modelA.npz")}
    existing_b = {f.stem.replace("_modelB", "") for f in output_path.glob("conv_*_modelB.npz")}
    existing_convs = existing_a & existing_b  # only count fully-saved pairs
    num_existing = len(existing_convs)

    # Get temperature from lm_gen_a
    temperature = getattr(lm_gen_a, "temp", 0.8)

    stats = {
        "batch_id": batch_id,
        "mode": "cross_play",
        "target_conversations": num_conversations,
        "accepted": num_existing,
        "rejected": 0,
        "rejection_reasons": {},
        "total_valid_steps": 0,
        "total_wall_time_s": 0.0,
        "per_seed_type": {st: {"accepted": 0, "rejected": 0} for st in seed_types},
        "resumed_from": num_existing,
        "top_k_logits": top_k_logits,
        "steps_per_conversation": steps_per_conversation,
        "npz_files_saved": num_existing * 2,
    }

    rng = np.random.default_rng(seed=start_index)
    weights = np.array(seed_type_weights, dtype=np.float64)
    weights /= weights.sum()

    attempt = 0
    t_start = time.time()

    if num_existing > 0:
        print(f"📂 Resuming: found {num_existing} existing cross-play "
              f"conversations in {output_path}")

    pbar = tqdm(
        total=num_conversations, initial=num_existing,
        desc=f"Cross-play {batch_id}",
    )

    while stats["accepted"] < num_conversations:
        seed_idx = start_index + attempt
        seed_type = rng.choice(seed_types, p=weights)
        conv_id = f"conv_{seed_idx:06d}"

        if conv_id in existing_convs:
            attempt += 1
            continue

        try:
            record = generate_cross_play_conversation(
                lm_gen_a=lm_gen_a,
                lm_gen_b=lm_gen_b,
                num_steps=steps_per_conversation,
                seed_type=seed_type,
                seed_index=seed_idx,
                top_k_logits=top_k_logits,
                conv_id=conv_id,
                card=card,
                device=device,
                repetition_penalty=repetition_penalty,
                rep_window=rep_window,
            )
            record.temperature = temperature

            # Quality-filter BOTH streams — reject if either fails
            quality_a = filter_conversation(
                text_tokens=record.a_text_tokens,
                audio_tokens=record.a_audio_tokens,
                num_valid_steps=record.num_valid_steps,
            )
            quality_b = filter_conversation(
                text_tokens=record.b_text_tokens,
                audio_tokens=record.b_audio_tokens,
                num_valid_steps=record.num_valid_steps,
            )
            record.quality_a = quality_a
            record.quality_b = quality_b

            if quality_a.accepted and quality_b.accepted:
                save_cross_play_conversation(record, output_path)
                stats["accepted"] += 1
                stats["total_valid_steps"] += record.num_valid_steps
                stats["per_seed_type"][seed_type]["accepted"] += 1
                stats["npz_files_saved"] += 2
                pbar.update(1)
            else:
                stats["rejected"] += 1
                # Report which side failed
                if not quality_a.accepted:
                    reason = f"modelA: {quality_a.rejection_reason}"
                else:
                    reason = f"modelB: {quality_b.rejection_reason}"
                stats["rejection_reasons"][reason] = (
                    stats["rejection_reasons"].get(reason, 0) + 1
                )
                stats["per_seed_type"][seed_type]["rejected"] += 1
                if save_rejected:
                    save_cross_play_conversation(
                        record, output_path / "rejected"
                    )

        except Exception as e:
            stats["rejected"] += 1
            reason = f"error: {type(e).__name__}"
            stats["rejection_reasons"][reason] = (
                stats["rejection_reasons"].get(reason, 0) + 1
            )
            print(f"⚠️  Error generating {conv_id}: {e}")

        attempt += 1

        if attempt > num_conversations * 3:
            print(f"⚠️  Giving up after {attempt} attempts "
                  f"({stats['accepted']} accepted, {stats['rejected']} rejected)")
            break

    pbar.close()
    stats["total_wall_time_s"] = time.time() - t_start
    stats["total_attempts"] = attempt
    stats["acceptance_rate"] = stats["accepted"] / max(1, attempt)
    stats["total_audio_hours"] = (
        stats["total_valid_steps"] / 12.5 / 3600
    )
    # Cross-play doubles training data (2 .npz per conversation)
    stats["total_training_hours"] = stats["total_audio_hours"] * 2

    meta_path = output_path / "batch_meta.json"
    with open(meta_path, "w") as f:
        json.dump(stats, f, indent=2, default=str)
    print(
        f"\n✅ Batch {batch_id}: {stats['accepted']} cross-play conversations, "
        f"{stats['total_audio_hours']:.2f} hrs audio "
        f"({stats['total_training_hours']:.2f} hrs training data), "
        f"{stats['total_wall_time_s'] / 60:.1f} min wall time, "
        f"{stats['acceptance_rate']:.1%} acceptance rate"
    )

    return stats
