"""Hook-based teacher target capture during self-play generation.

Installs forward hooks on LMGen / LMModel to capture:
  - Sparse top-K text logits (from Temporal Transformer text head)
  - Sparse top-K audio CB0 logits (from Depformer linear[0])
  - Sampled text tokens (Inner Monologue)
  - Sampled audio tokens (all 8 codebooks from Depformer)

All targets are captured *during* the generation step — no separate
target extraction pass is needed.
"""

import torch
from dataclasses import dataclass, field


@dataclass
class StepTargets:
    """Targets captured from a single self-play timestep."""
    text_logits_vals: torch.Tensor    # [top_k], float16
    text_logits_idxs: torch.Tensor    # [top_k], int32
    audio_cb0_logits_vals: torch.Tensor  # [top_k], float16
    audio_cb0_logits_idxs: torch.Tensor  # [top_k], int32
    text_token: int                   # scalar — sampled Inner Monologue token
    audio_tokens: torch.Tensor        # [dep_q=8], int16 — all 8 audio CB tokens


class TeacherTargetCapture:
    """Wraps LMGen to capture teacher targets inline during self-play.

    Usage::

        capture = TeacherTargetCapture(lm_gen, top_k=50)
        capture.install_hooks()

        with lm_gen.streaming(batch_size=1):
            for t in range(num_steps):
                out = lm_gen.step(input_tokens)
                targets = capture.pop_step_targets()
                # targets is a StepTargets instance (or None if not ready)

        capture.remove_hooks()

    Architecture note (Moshiko config):
        n_q=16, dep_q=8, num_codebooks=17
        - Codebooks 0..7: user audio (Channel A) — fed as input_tokens
        - Codebooks 8..15: model audio (Channel B) — generated by Depformer
        - Codebook 16 (index 0 in the state): text (Inner Monologue)

    The Depformer generates dep_q=8 audio codebooks. At cb_index=0 inside
    depformer_step, the model predicts the FIRST model audio codebook (CB8
    overall, CB0 of the model's stream). We capture logits from self.linears[0]
    which is this first model audio codebook.
    """

    def __init__(self, lm_gen, top_k: int = 50):
        self.lm_gen = lm_gen
        self.lm_model = lm_gen.lm_model
        self.top_k = top_k
        self._hooks: list = []
        self._current: dict = {}

    def install_hooks(self):
        """Install capture hooks on LMGen and LMModel."""
        # 1. Text logits — via built-in LMGen hook
        self._orig_text_logits_hook = self.lm_gen.on_text_logits_hook

        def _text_logits_hook(logits):
            # logits: [B, 1, 1, text_card=32000]
            logit_vec = logits[0, 0, 0]  # [text_card]
            vals, idxs = logit_vec.topk(min(self.top_k, logit_vec.shape[0]))
            self._current["text_logits_vals_gpu"] = vals.half()
            self._current["text_logits_idxs_gpu"] = idxs.int()
            if self._orig_text_logits_hook:
                self._orig_text_logits_hook(logits)

        self.lm_gen.on_text_logits_hook = _text_logits_hook

        # 2. Text token — via built-in LMGen hook
        self._orig_text_hook = self.lm_gen.on_text_hook

        def _text_hook(token):
            # token: [B] = [1]
            self._current["text_token_gpu"] = token[0]
            if self._orig_text_hook:
                self._orig_text_hook(token)

        self.lm_gen.on_text_hook = _text_hook

        # 3. Audio tokens — via built-in LMGen hook
        self._orig_audio_hook = self.lm_gen.on_audio_hook

        def _audio_hook(tokens):
            # tokens: [B, dep_q] = [1, 8]
            self._current["audio_tokens_gpu"] = tokens[0].to(torch.int16)
            if self._orig_audio_hook:
                self._orig_audio_hook(tokens)

        self.lm_gen.on_audio_hook = _audio_hook

        # 4. Audio CB0 logits — forward hook on self.linears[0]
        #    This captures the Depformer's output logits for the first
        #    model audio codebook BEFORE sampling.
        def _cb0_logit_hook(module, input, output):
            # During streaming: output is [B, 1, card=2048] or [B*T, card]
            # LMGen.depformer_step calls linears[0] with [B, 1, depformer_dim]
            # producing [B, 1, card]. But the norm is applied before linear,
            # so the hook fires on the linear output directly.
            out = output
            if out.dim() == 3:
                out = out[0, 0]  # [card]
            elif out.dim() == 2:
                out = out[0]  # [card]
            else:
                return  # unexpected shape, skip
            vals, idxs = out.topk(min(self.top_k, out.shape[0]))
            self._current["audio_cb0_logits_vals_gpu"] = vals.half()
            self._current["audio_cb0_logits_idxs_gpu"] = idxs.int()

        h = self.lm_model.linears[0].register_forward_hook(_cb0_logit_hook)
        self._hooks.append(h)

    def pop_step_targets(self) -> StepTargets | None:
        """Return targets from the most recent step, or None if incomplete.

        Clears internal buffer after returning.
        """
        c = self._current
        required = [
            "text_logits_vals_gpu", "text_logits_idxs_gpu",
            "audio_cb0_logits_vals_gpu", "audio_cb0_logits_idxs_gpu",
            "text_token_gpu", "audio_tokens_gpu",
        ]
        if not all(k in c for k in required):
            return None

        targets = StepTargets(
            text_logits_vals=c["text_logits_vals_gpu"].cpu(),
            text_logits_idxs=c["text_logits_idxs_gpu"].cpu(),
            audio_cb0_logits_vals=c["audio_cb0_logits_vals_gpu"].cpu(),
            audio_cb0_logits_idxs=c["audio_cb0_logits_idxs_gpu"].cpu(),
            text_token=c["text_token_gpu"].item(),
            audio_tokens=c["audio_tokens_gpu"].cpu(),
        )
        self._current = {}
        return targets

    def remove_hooks(self):
        """Remove all installed hooks and restore originals."""
        for h in self._hooks:
            h.remove()
        self._hooks.clear()

        # Restore original hooks
        self.lm_gen.on_text_logits_hook = getattr(self, "_orig_text_logits_hook", None)
        self.lm_gen.on_text_hook = getattr(self, "_orig_text_hook", None)
        self.lm_gen.on_audio_hook = getattr(self, "_orig_audio_hook", None)
